name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - pandas
  - bqplot
  - ipycanvas
  - ipywidgets
  - folium
  - numpy
  - pillow
  - pip
  - pip:
    - requests
