name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - bqplot
  - ipywidgets
  - pandas
  - numpy
  - urllib3
  - idna
  - certifi
  - charset-normalizer
  - blinker
  - pip
  - pip: 
    - requests
    - pyarrow
    - streamlit
